[tool.poetry]
name = "f1-stream"
version = "0.1.0"
description = ""
authors = ["mrkeuz <mrkeuz@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"
psutil = "^5.9.0"
loguru = "^0.6.0"
cached-property = "^1.5.2"
profilehooks = "^1.12.0"
xprintidle = "^0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
